# Generated by Django 5.2.16 on 2026-07-20 20:55

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenancy', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ManagedCustomer',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('internal_code', models.CharField(blank=True, max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='tenancy.organization')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Site',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('code', models.CharField(blank=True, max_length=50)),
                ('site_type', models.CharField(choices=[('OFFICE', 'Oficina'), ('DATACENTER', 'Datacenter'), ('CLOUD', 'Cloud'), ('SAAS', 'SaaS'), ('OTHER', 'Otro')], default='OTHER', max_length=20)),
                ('timezone', models.CharField(default='America/Argentina/Buenos_Aires', max_length=64)),
                ('is_active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True)),
                ('managed_customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sites', to='customers.managedcustomer')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='tenancy.organization')),
            ],
            options={
                'ordering': ['managed_customer__name', 'name'],
            },
        ),
        migrations.AddConstraint(
            model_name='managedcustomer',
            constraint=models.UniqueConstraint(fields=('organization', 'name'), name='uq_managed_customer_name_per_organization'),
        ),
        migrations.AddConstraint(
            model_name='managedcustomer',
            constraint=models.UniqueConstraint(condition=models.Q(('internal_code', ''), _negated=True), fields=('organization', 'internal_code'), name='uq_managed_customer_code_per_organization'),
        ),
        migrations.AddConstraint(
            model_name='site',
            constraint=models.UniqueConstraint(fields=('organization', 'managed_customer', 'name'), name='uq_site_name_per_customer_organization'),
        ),
    ]
