# Generated by Django 5.2.16 on 2026-07-20 21:03

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0001_initial'),
        ('inventory', '0001_initial'),
        ('tenancy', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BackupJob',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('external_identifier', models.CharField(blank=True, max_length=160)),
                ('matching_aliases', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('ACTIVE', 'Activa'), ('PAUSED', 'Pausada'), ('RETIRED', 'Retirada')], default='ACTIVE', max_length=20)),
                ('criticality', models.CharField(choices=[('LOW', 'Baja'), ('MEDIUM', 'Media'), ('HIGH', 'Alta'), ('CRITICAL', 'Crítica')], default='MEDIUM', max_length=20)),
                ('internal_owner', models.CharField(blank=True, max_length=120)),
                ('notes', models.TextField(blank=True)),
                ('managed_customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='backup_jobs', to='customers.managedcustomer')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='tenancy.organization')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='backup_jobs', to='customers.site')),
            ],
            options={
                'ordering': ['managed_customer__name', 'site__name', 'name'],
            },
        ),
        migrations.CreateModel(
            name='BackupConfigurationChange',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('summary', models.CharField(max_length=255)),
                ('reason', models.TextField(blank=True)),
                ('before', models.JSONField(blank=True, default=dict)),
                ('after', models.JSONField(blank=True, default=dict)),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='backup_configuration_changes', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='tenancy.organization')),
                ('backup_job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='configuration_changes', to='backups.backupjob')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BackupSchedule',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('frequency', models.CharField(choices=[('DAILY', 'Diaria'), ('WEEKLY', 'Semanal'), ('MONTHLY', 'Mensual'), ('CUSTOM', 'Personalizada')], max_length=20)),
                ('weekdays', models.CharField(blank=True, help_text='Comma-separated ISO weekdays, 1=Monday through 7=Sunday.', max_length=80)),
                ('scheduled_time', models.TimeField()),
                ('timezone', models.CharField(default='America/Argentina/Buenos_Aires', max_length=64)),
                ('cron_expression', models.CharField(blank=True, max_length=120)),
                ('expected_duration_minutes', models.PositiveIntegerField(default=60)),
                ('report_deadline_time', models.TimeField()),
                ('report_deadline_offset_days', models.PositiveSmallIntegerField(default=1)),
                ('mode', models.CharField(choices=[('AUTOMATIC', 'Automática'), ('MANUAL', 'Manual'), ('ASSISTED', 'Asistida')], default='AUTOMATIC', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True)),
                ('backup_job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='backups.backupjob')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='tenancy.organization')),
            ],
            options={
                'ordering': ['backup_job__name', 'scheduled_time'],
            },
        ),
        migrations.CreateModel(
            name='BackupTechnology',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=120)),
                ('vendor', models.CharField(blank=True, max_length=120)),
                ('is_active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='tenancy.organization')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='backupjob',
            name='technology',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='backup_jobs', to='backups.backuptechnology'),
        ),
        migrations.CreateModel(
            name='RetentionPolicy',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('daily_copies', models.PositiveSmallIntegerField(default=0)),
                ('weekly_copies', models.PositiveSmallIntegerField(default=0)),
                ('monthly_copies', models.PositiveSmallIntegerField(default=0)),
                ('annual_copies', models.PositiveSmallIntegerField(default=0)),
                ('total_days', models.PositiveIntegerField(default=0)),
                ('uses_gfs', models.BooleanField(default=False)),
                ('deleted_item_retention_days', models.PositiveIntegerField(default=0)),
                ('notes', models.TextField(blank=True)),
                ('backup_job', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='retention_policy', to='backups.backupjob')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='tenancy.organization')),
            ],
            options={
                'verbose_name_plural': 'Retention policies',
            },
        ),
        migrations.CreateModel(
            name='BackupDestination',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('repository_type', models.CharField(max_length=80)),
                ('name', models.CharField(max_length=160)),
                ('location', models.CharField(blank=True, max_length=255)),
                ('capacity_gb', models.PositiveIntegerField(blank=True, null=True)),
                ('free_space_threshold_gb', models.PositiveIntegerField(blank=True, null=True)),
                ('is_offsite', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='tenancy.organization')),
                ('backup_job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='destinations', to='backups.backupjob')),
            ],
            options={
                'ordering': ['backup_job__name', 'name'],
                'constraints': [models.UniqueConstraint(fields=('organization', 'backup_job', 'name'), name='uq_backup_destination_name_per_job_organization')],
            },
        ),
        migrations.CreateModel(
            name='BackupJobTarget',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('role', models.CharField(choices=[('PRIMARY', 'Principal'), ('INCLUDED', 'Incluido'), ('EXCLUDED', 'Excluido'), ('DEPENDENCY', 'Dependencia'), ('OTHER', 'Otro')], default='PRIMARY', max_length=20)),
                ('inclusions', models.TextField(blank=True)),
                ('exclusions', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('backup_job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='targets', to='backups.backupjob')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='tenancy.organization')),
                ('protected_object', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='backup_targets', to='inventory.protectedobject')),
            ],
            options={
                'ordering': ['backup_job__name', 'protected_object__name'],
                'constraints': [models.UniqueConstraint(fields=('organization', 'backup_job', 'protected_object'), name='uq_backup_job_target_per_organization')],
            },
        ),
        migrations.AddConstraint(
            model_name='backuptechnology',
            constraint=models.UniqueConstraint(fields=('organization', 'name'), name='uq_backup_technology_name_per_organization'),
        ),
        migrations.AddConstraint(
            model_name='backupjob',
            constraint=models.UniqueConstraint(fields=('organization', 'managed_customer', 'site', 'name'), name='uq_backup_job_name_per_site_organization'),
        ),
        migrations.AddConstraint(
            model_name='backupjob',
            constraint=models.UniqueConstraint(condition=models.Q(('external_identifier', ''), _negated=True), fields=('organization', 'external_identifier'), name='uq_backup_job_external_identifier_per_organization'),
        ),
    ]
