# Generated by Django 5.2.16 on 2026-07-20 22:13

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ingestion', '0001_initial'),
        ('tenancy', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ParsedReportItem',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('item_index', models.PositiveSmallIntegerField(default=0)),
                ('parser_name', models.CharField(max_length=120)),
                ('parser_version', models.CharField(max_length=40)),
                ('parser_status', models.CharField(choices=[('SUCCESS', 'Correcto'), ('WARNING', 'Warning'), ('FAILED', 'Fallido'), ('PARTIAL', 'Parcial'), ('UNKNOWN', 'Desconocido')], max_length=20)),
                ('review_status', models.CharField(choices=[('AUTO_VALIDATED', 'Validado automáticamente'), ('NEEDS_REVIEW', 'Requiere revisión'), ('REVIEWED', 'Revisado'), ('REJECTED', 'Rechazado')], default='NEEDS_REVIEW', max_length=20)),
                ('occurred_at', models.DateTimeField(blank=True, null=True)),
                ('customer_hints', models.JSONField(blank=True, default=list)),
                ('object_hints', models.JSONField(blank=True, default=list)),
                ('job_hints', models.JSONField(blank=True, default=list)),
                ('summary', models.TextField(blank=True)),
                ('error_code', models.CharField(blank=True, max_length=120)),
                ('error_details', models.TextField(blank=True)),
                ('warning_details', models.TextField(blank=True)),
                ('metrics', models.JSONField(blank=True, default=dict)),
                ('confidence', models.FloatField(default=0.0)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('review_note', models.TextField(blank=True)),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parsed_items', to='ingestion.inboundmessage')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='tenancy.organization')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_parsed_report_items', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at', 'message__received_at'],
                'constraints': [models.UniqueConstraint(fields=('organization', 'message', 'parser_name', 'parser_version', 'item_index'), name='uq_parsed_report_item_parser_index_per_message_org')],
            },
        ),
    ]
