# Generated by Django 5.2.16 on 2026-07-21 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parsers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parsedreportitem',
            name='parser_status',
            field=models.CharField(choices=[('SUCCESS', 'Correcto'), ('WARNING', 'Warning'), ('FAILED', 'Fallido'), ('PARTIAL', 'Parcial'), ('RUNNING', 'En curso'), ('CANCELED', 'Cancelado'), ('UNKNOWN', 'Desconocido')], max_length=20),
        ),
    ]
