# Generated by Django 5.2.16 on 2026-07-20 21:30

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenancy', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MailConnector',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=160)),
                ('provider_type', models.CharField(choices=[('MICROSOFT_GRAPH', 'Microsoft 365 Outlook'), ('IMAP', 'IMAP'), ('GMAIL_API', 'Gmail API')], max_length=30)),
                ('auth_mode', models.CharField(choices=[('OAUTH_CLIENT_CREDENTIALS', 'OAuth client credentials'), ('OAUTH_REFRESH_TOKEN', 'OAuth refresh token'), ('BASIC_ENV', 'Basic credentials from environment')], max_length=40)),
                ('mailbox_address', models.EmailField(max_length=254)),
                ('folder', models.CharField(default='Inbox', max_length=160)),
                ('config', models.JSONField(blank=True, default=dict)),
                ('read_only', models.BooleanField(default=True)),
                ('poll_interval_seconds', models.PositiveIntegerField(default=300)),
                ('last_synced_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mail_connectors', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='tenancy.organization')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='InboundMessage',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('external_message_id', models.CharField(max_length=512)),
                ('internet_message_id', models.CharField(blank=True, max_length=512)),
                ('conversation_id', models.CharField(blank=True, max_length=512)),
                ('subject', models.CharField(blank=True, max_length=998)),
                ('sender', models.EmailField(blank=True, max_length=254)),
                ('recipients', models.JSONField(blank=True, default=list)),
                ('received_at', models.DateTimeField(blank=True, null=True)),
                ('body_preview', models.TextField(blank=True)),
                ('raw_headers', models.JSONField(blank=True, default=dict)),
                ('provider_payload', models.JSONField(blank=True, default=dict)),
                ('content_hash', models.CharField(blank=True, max_length=64)),
                ('has_attachments', models.BooleanField(default=False)),
                ('parser_status', models.CharField(default='UNPROCESSED', max_length=40)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='tenancy.organization')),
                ('connector', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='messages', to='ingestion.mailconnector')),
            ],
            options={
                'ordering': ['-received_at', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MessageAttachment',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('filename', models.CharField(max_length=255)),
                ('content_type', models.CharField(blank=True, max_length=160)),
                ('size_bytes', models.PositiveIntegerField(default=0)),
                ('sha256', models.CharField(max_length=64)),
                ('storage_path', models.CharField(blank=True, max_length=512)),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='ingestion.inboundmessage')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='tenancy.organization')),
            ],
            options={
                'ordering': ['filename'],
            },
        ),
        migrations.AddConstraint(
            model_name='mailconnector',
            constraint=models.UniqueConstraint(fields=('organization', 'name'), name='uq_mail_connector_name_per_organization'),
        ),
        migrations.AddConstraint(
            model_name='mailconnector',
            constraint=models.CheckConstraint(condition=models.Q(('read_only', True)), name='ck_mail_connector_read_only'),
        ),
        migrations.AddConstraint(
            model_name='inboundmessage',
            constraint=models.UniqueConstraint(fields=('organization', 'connector', 'external_message_id'), name='uq_inbound_message_external_id_per_connector_org'),
        ),
        migrations.AddConstraint(
            model_name='messageattachment',
            constraint=models.UniqueConstraint(fields=('organization', 'message', 'sha256', 'filename'), name='uq_message_attachment_hash_name_per_org'),
        ),
    ]
