# Generated by Django 5.2.16 on 2026-07-21 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingestion', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='inboundmessage',
            name='html_as_text',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='inboundmessage',
            name='html_body',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='inboundmessage',
            name='text_body',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='messageattachment',
            name='extracted_text',
            field=models.TextField(blank=True),
        ),
    ]
