# Generated by Django 5.2.16 on 2026-07-20 20:55

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0001_initial'),
        ('tenancy', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProtectedObject',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('external_reference', models.CharField(blank=True, max_length=120)),
                ('object_type', models.CharField(choices=[('PHYSICAL_SERVER', 'Servidor físico'), ('VIRTUAL_SERVER', 'Servidor virtual'), ('VIRTUAL_MACHINE', 'Máquina virtual'), ('APPLICATION', 'Aplicación'), ('DATABASE', 'Base de datos'), ('FILE_SET', 'Archivos o carpetas'), ('NAS', 'NAS'), ('MICROSOFT_365_TENANT', 'Tenant Microsoft 365'), ('MAILBOX', 'Buzón'), ('CLOUD_RESOURCE', 'Recurso cloud'), ('SNAPSHOT', 'Snapshot'), ('OTHER', 'Otro')], max_length=40)),
                ('hostname', models.CharField(blank=True, max_length=255)),
                ('platform', models.CharField(blank=True, max_length=120)),
                ('criticality', models.CharField(blank=True, max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True)),
                ('managed_customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='protected_objects', to='customers.managedcustomer')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='tenancy.organization')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='protected_objects', to='customers.site')),
            ],
            options={
                'ordering': ['managed_customer__name', 'site__name', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ObjectRelation',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('relation_type', models.CharField(choices=[('HOSTS', 'Aloja'), ('RUNS_ON', 'Corre sobre'), ('PART_OF', 'Parte de'), ('DEPENDS_ON', 'Depende de'), ('OTHER', 'Otra')], max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='tenancy.organization')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outgoing_relations', to='inventory.protectedobject')),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incoming_relations', to='inventory.protectedobject')),
            ],
            options={
                'ordering': ['source__name', 'relation_type', 'target__name'],
            },
        ),
        migrations.AddConstraint(
            model_name='protectedobject',
            constraint=models.UniqueConstraint(fields=('organization', 'managed_customer', 'site', 'name'), name='uq_protected_object_name_per_site_organization'),
        ),
        migrations.AddConstraint(
            model_name='protectedobject',
            constraint=models.UniqueConstraint(condition=models.Q(('external_reference', ''), _negated=True), fields=('organization', 'external_reference'), name='uq_protected_object_reference_per_organization'),
        ),
        migrations.AddConstraint(
            model_name='objectrelation',
            constraint=models.UniqueConstraint(fields=('organization', 'source', 'target', 'relation_type'), name='uq_object_relation_per_organization'),
        ),
        migrations.AddConstraint(
            model_name='objectrelation',
            constraint=models.CheckConstraint(condition=models.Q(('source', models.F('target')), _negated=True), name='ck_object_relation_no_self_link'),
        ),
    ]
