# Generated by Django 5.2.16 on 2026-07-20 21:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='protectedobject',
            name='uq_protected_object_reference_per_organization',
        ),
    ]
