# Generated by Django 5.2.16 on 2026-07-20 21:12

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('backups', '0001_initial'),
        ('inventory', '0002_remove_protectedobject_uq_protected_object_reference_per_organization'),
        ('tenancy', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyControlEntry',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('control_date', models.DateField()),
                ('result', models.CharField(choices=[('PENDING', 'Pendiente'), ('SUCCESS', 'Correcto'), ('WARNING', 'Warning'), ('ERROR', 'Error'), ('NO_REPORT', 'Sin reporte'), ('JUSTIFIED', 'Justificado')], default='PENDING', max_length=20)),
                ('observed_at', models.DateTimeField(blank=True, null=True)),
                ('system_summary', models.TextField(blank=True)),
                ('manual_observation', models.TextField(blank=True)),
                ('ticket_reference', models.CharField(blank=True, max_length=120)),
                ('is_active', models.BooleanField(default=True)),
                ('backup_job', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='daily_control_entries', to='backups.backupjob')),
                ('backup_job_target', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='daily_control_entries', to='backups.backupjobtarget')),
                ('operator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='daily_control_entries', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='tenancy.organization')),
                ('protected_object', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='daily_control_entries', to='inventory.protectedobject')),
            ],
            options={
                'ordering': ['-control_date', 'backup_job__name', 'protected_object__name'],
                'constraints': [models.UniqueConstraint(fields=('organization', 'control_date', 'backup_job', 'protected_object'), name='uq_daily_control_job_object_date_per_organization')],
            },
        ),
    ]
