# Generated by Django 5.2.16 on 2026-07-20 21:20

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backups', '0001_initial'),
        ('operations', '0001_initial'),
        ('tenancy', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExpectedExecution',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('service_date', models.DateField()),
                ('scheduled_start_at', models.DateTimeField()),
                ('report_deadline_at', models.DateTimeField()),
                ('status', models.CharField(choices=[('WAITING_REPORT', 'Esperando reporte'), ('SUCCESS', 'Correcto'), ('WARNING', 'Warning'), ('ERROR', 'Error'), ('NO_REPORT', 'Sin reporte'), ('JUSTIFIED', 'Justificado'), ('CANCELLED', 'Cancelado')], default='WAITING_REPORT', max_length=20)),
                ('system_summary', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('backup_job', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='expected_executions', to='backups.backupjob')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='tenancy.organization')),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='expected_executions', to='backups.backupschedule')),
            ],
            options={
                'ordering': ['service_date', 'scheduled_start_at', 'backup_job__name'],
            },
        ),
        migrations.AddField(
            model_name='dailycontrolentry',
            name='expected_execution',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='daily_control_entries', to='operations.expectedexecution'),
        ),
        migrations.AddConstraint(
            model_name='expectedexecution',
            constraint=models.UniqueConstraint(fields=('organization', 'schedule', 'service_date'), name='uq_expected_execution_schedule_date_per_organization'),
        ),
    ]
