# Generated by Django 5.2.16 on 2026-07-21 01:48

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backups', '0001_initial'),
        ('operations', '0002_expectedexecution_and_more'),
        ('parsers', '0001_initial'),
        ('tenancy', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BackupExecution',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('service_date', models.DateField()),
                ('occurred_at', models.DateTimeField(blank=True, null=True)),
                ('result', models.CharField(choices=[('SUCCESS', 'Correcto'), ('WARNING', 'Advertencia'), ('ERROR', 'Error'), ('NO_REPORT', 'Sin reporte'), ('UNKNOWN', 'Desconocido'), ('JUSTIFIED', 'Justificado'), ('CANCELLED', 'Cancelado')], max_length=20)),
                ('match_status', models.CharField(choices=[('NEEDS_REVIEW', 'Requiere revisión'), ('MANUAL_MATCHED', 'Asociado manualmente'), ('AUTO_MATCHED', 'Asociado automáticamente'), ('REJECTED', 'Rechazado')], default='NEEDS_REVIEW', max_length=30)),
                ('confidence', models.FloatField(default=0.0)),
                ('parser_summary', models.TextField(blank=True)),
                ('operator_note', models.TextField(blank=True)),
                ('matched_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('backup_job', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='backup_executions', to='backups.backupjob')),
                ('expected_execution', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='backup_executions', to='operations.expectedexecution')),
                ('matched_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='matched_backup_executions', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='tenancy.organization')),
                ('parsed_item', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='backup_execution', to='parsers.parsedreportitem')),
            ],
            options={
                'ordering': ['-service_date', 'backup_job__name', '-created_at'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('parsed_item__isnull', False)), fields=('organization', 'parsed_item'), name='uq_backup_execution_parsed_item_per_org')],
            },
        ),
    ]
