# Generated by Django 5.2.16 on 2026-07-21 20:01

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
        ('imports', '0001_initial'),
        ('tenancy', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='importbatch',
            name='delimiter',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='importbatch',
            name='dry_run',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='importbatch',
            name='encoding',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name='importbatch',
            name='source_sha256',
            field=models.CharField(blank=True, db_index=True, max_length=64),
        ),
        migrations.AddField(
            model_name='importbatch',
            name='summary_json',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.CreateModel(
            name='LegacyBackupConfiguration',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('source_sha256', models.CharField(max_length=64)),
                ('source_row', models.PositiveIntegerField()),
                ('legacy_fingerprint', models.CharField(max_length=64)),
                ('legacy_customer_name', models.CharField(max_length=255)),
                ('legacy_site_label', models.CharField(blank=True, max_length=255)),
                ('source_asset_label', models.CharField(blank=True, max_length=255)),
                ('legacy_backup_name', models.CharField(blank=True, max_length=255)),
                ('legacy_method', models.CharField(blank=True, max_length=160)),
                ('provider', models.CharField(blank=True, max_length=80)),
                ('provider_requires_confirmation', models.BooleanField(default=False)),
                ('external_responsible', models.TextField(blank=True)),
                ('is_external', models.BooleanField(default=False)),
                ('schedule_hint', models.TextField(blank=True)),
                ('schedule_requires_confirmation', models.BooleanField(default=False)),
                ('quality_flags', models.JSONField(blank=True, default=list)),
                ('import_batch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='legacy_backup_configurations', to='imports.importbatch')),
                ('managed_customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='legacy_backup_configurations', to='customers.managedcustomer')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='tenancy.organization')),
            ],
            options={
                'ordering': ['legacy_customer_name', 'source_row'],
            },
        ),
        migrations.CreateModel(
            name='LegacyDailyRecord',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('source_sha256', models.CharField(max_length=64)),
                ('source_row', models.PositiveIntegerField()),
                ('source_date', models.DateField()),
                ('raw_responsible', models.TextField(blank=True)),
                ('raw_status', models.CharField(blank=True, max_length=80)),
                ('raw_ticket', models.CharField(blank=True, max_length=120)),
                ('raw_observation', models.TextField(blank=True)),
                ('normalized_status', models.CharField(max_length=40)),
                ('normalization_rule', models.CharField(blank=True, max_length=120)),
                ('quality_flags', models.JSONField(blank=True, default=list)),
                ('backup_configuration', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='daily_records', to='imports.legacybackupconfiguration')),
                ('import_batch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='legacy_daily_records', to='imports.importbatch')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='tenancy.organization')),
            ],
            options={
                'ordering': ['source_date', 'source_row'],
            },
        ),
        migrations.CreateModel(
            name='LegacyImportIssue',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('source_sha256', models.CharField(max_length=64)),
                ('source_row', models.PositiveIntegerField()),
                ('source_date', models.DateField(blank=True, null=True)),
                ('issue_code', models.CharField(max_length=80)),
                ('severity', models.CharField(max_length=20)),
                ('details', models.TextField(blank=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('import_batch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='legacy_import_issues', to='imports.importbatch')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='tenancy.organization')),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_legacy_import_issues', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['source_row', 'source_date', 'issue_code'],
            },
        ),
        migrations.CreateModel(
            name='LegacyTicketReference',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('external_system', models.CharField(choices=[('MANAGEENGINE', 'ManageEngine')], default='MANAGEENGINE', max_length=40)),
                ('external_id', models.CharField(max_length=120)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='tenancy.organization')),
            ],
            options={
                'ordering': ['external_id'],
            },
        ),
        migrations.AddConstraint(
            model_name='legacybackupconfiguration',
            constraint=models.UniqueConstraint(fields=('organization', 'source_sha256', 'legacy_fingerprint'), name='uq_legacy_backup_config_fingerprint_per_source_org'),
        ),
        migrations.AddConstraint(
            model_name='legacydailyrecord',
            constraint=models.UniqueConstraint(fields=('organization', 'source_sha256', 'source_row', 'source_date'), name='uq_legacy_daily_record_source_row_date_per_org'),
        ),
        migrations.AddConstraint(
            model_name='legacyimportissue',
            constraint=models.UniqueConstraint(fields=('organization', 'source_sha256', 'source_row', 'source_date', 'issue_code'), name='uq_legacy_import_issue_source_row_date_code_per_org'),
        ),
        migrations.AddConstraint(
            model_name='legacyticketreference',
            constraint=models.UniqueConstraint(fields=('organization', 'external_system', 'external_id'), name='uq_legacy_ticket_reference_external_id_per_org'),
        ),
    ]
