# Generated by Django 5.2.16 on 2026-07-21 20:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backups', '0001_initial'),
        ('customers', '0001_initial'),
        ('imports', '0002_importbatch_delimiter_importbatch_dry_run_and_more'),
        ('inventory', '0002_remove_protectedobject_uq_protected_object_reference_per_organization'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='legacybackupconfiguration',
            name='reconciled_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='legacybackupconfiguration',
            name='reconciled_backup_job',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reconciled_legacy_backup_configurations', to='backups.backupjob'),
        ),
        migrations.AddField(
            model_name='legacybackupconfiguration',
            name='reconciled_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reconciled_legacy_backup_configurations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='legacybackupconfiguration',
            name='reconciled_protected_object',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reconciled_legacy_backup_configurations', to='inventory.protectedobject'),
        ),
        migrations.AddField(
            model_name='legacybackupconfiguration',
            name='reconciled_site',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reconciled_legacy_backup_configurations', to='customers.site'),
        ),
        migrations.AddField(
            model_name='legacybackupconfiguration',
            name='reconciliation_note',
            field=models.TextField(blank=True),
        ),
    ]
